###########################################################

ifeq (,$(PLATFORM))
PLATFORM=$(UNION_PLATFORM)
endif

ifeq (,$(PLATFORM))
$(error please specify PLATFORM, eg. PLATFORM=trimui make)
endif

###########################################################

all:
	# $(PLATFORM) all
	# cd overclock && make

clean:
	# $(PLATFORM) clean
	
	