###########################################################

ifeq (,$(PLATFORM))
PLATFORM=$(UNION_PLATFORM)
endif

ifeq (,$(PLATFORM))
$(error please specify PLATFORM, eg. PLATFORM=rg353 make)
endif

###########################################################

all: 
	# all
	
early:
	# early

clean:
	#clean

###########################################################
