$(PLATFORM):
	# $@
	cp ./workspace/$@/show/show.elf ./build/SYSTEM/$@/bin
	# installer
	cp ./workspace/$@/install/boot.sh ./build/BOOT/common/$@.sh
	mkdir -p ./build/BOOT/common/$@/
	cp ./workspace/$@/install/*.png ./build/BOOT/common/$@/
	cp ./workspace/$@/show/show.elf ./build/BOOT/common/$@/
	cp ./workspace/tg5040/other/unzip60/unzip ./build/BOOT/common/$@/
	# extras
	# cp ./workspace/tg5040/other/evtest/evtest ./build/EXTRAS/Tools/$@/Developer.pak/
