$(PLATFORM):
	# $@
	cp ./workspace/$@/blank/blank.elf ./build/SYSTEM/$@/bin/
	cp ./workspace/$@/batmon/batmon.elf ./build/SYSTEM/$@/bin/
	cp ./workspace/$@/lumon/lumon.elf ./build/SYSTEM/$@/bin/
	cp ./workspace/$@/other/sdl/build/.libs/libSDL-1.2.so.0.11.5 ./build/SYSTEM/$@/lib/libSDL-1.2.so.0
	cp ./workspace/$@/other/latency_reduction/as_preload.so ./build/SYSTEM/$@/lib/
	cp ./workspace/$@/other/latency_reduction/audioserver.mod ./build/SYSTEM/$@/bin/