$(PLATFORM):
	# $@
	# installer (new)
	mkdir -p ./build/BASE/trimui/app
	cp ./workspace/$@/install/boot.sh ./build/BOOT/$@.sh
	# extras
	cp ./workspace/$@/other/DinguxCommander/output/DinguxCommander ./build/EXTRAS/Tools/$@/Files.pak/
	cp -r ./workspace/$@/other/DinguxCommander/res ./build/EXTRAS/Tools/$@/Files.pak/
