$(PLATFORM):
	# $@
	cp ./workspace/$@/init/init.elf ./build/SYSTEM/$@/bin/
	# move libs (copied from toolchain)
	mv ./workspace/libSDL2_image-2.0.so.0 ./build/SYSTEM/$@/lib/
	mv ./workspace/libSDL2_ttf-2.0.so.0 ./build/SYSTEM/$@/lib/