$(PLATFORM):
	# $@
	cp ./workspace/$@/init/init.elf ./build/SYSTEM/$@/bin/
	cp ./workspace/$@/install/install.sh ./build/SYSTEM/$@/bin/
	cp ./workspace/$@/boot/output/dmenu.bin ./build/SYSTEM/$@/dat/
	mkdir -p ./build/BASE/$@
	cp ./workspace/$@/boot/output/dmenu.bin ./build/BASE/$@/
	cp ./workspace/$@/show/show.elf ./build/SYSTEM/$@/bin
	# move libs (copied from toolchain)
	mv ./workspace/libSDL2_image-2.0.so.0 ./build/SYSTEM/$@/lib/
	mv ./workspace/libSDL2_ttf-2.0.so.0 ./build/SYSTEM/$@/lib/